server:
  port: 80

spring:
  application:
    name: Order-Payment-Server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.43.168:3306/db2019?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka

CLOUD-PAYMENT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    com.order.springcloud.fengn.OrderServerFeign: debug

