server:
  port: 9000

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://euraka-one:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: cloud-gateway-one

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #无固定规则但要求唯一 路由id
          uri: lb://CLOUD-PAYMENT-SERVICE/
          predicates:
            - Path=/payment/** #断言路径匹配的进行路由
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/create/info/
#        - id: payment_routh3
#          uri: http://news.baidu.com/guonei
#          predicates:
#              - Path=/ll