server:
  port: 3444

eureka:
  instance:
    hostname: server-config
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://euraka-one:7001/eureka/
spring:
  application:
    name: spring-clouf-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianwei181111/springcloud-config.git
          search-paths:
            - spring-cloud-config-center/src/main/resources
          username: 1097708725@qq.com
          password: TIANwei123
      label: master
  profiles:
    active: dev
config:
  info: version 1